name: Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Playwright
        run: |
          npm -g i playwright@1.46.1
          npx playwright install --with-deps chromium
      - name: Run headless tests
        run: |
          node -e "const {chromium}=require('playwright');(async()=>{const b=await chromium.launch();const p=await b.newPage();await p.goto('file://' + process.cwd() + '/tests.html');const failures=await p.locator('.fail').count();await b.close();if(failures>0){console.error('Tests failed');process.exit(1);}console.log('All tests passed');})();"
